[project]
name = "docling-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "docling>=2.44.0",
    "easyocr>=1.7.1",
]

[project.scripts]
pdf-to-md = "src.pdf_to_markdown.cli:main"
